messages:
  inventory:
    name: "Town inventory"
  err:
    not_in_town: "You are not in town"
    only_materials: "In inventory you can put only materials!"
    only_mayor: "Only mayor can open town inventory!"
inventory:
  only_materials: false
  only_mayor: false